wandb:
  project: AEStest_exp
  project_name: 'AES'
  tags: [bert]
training:
  fold: 0
  test_size: 0.3
  n_epochs: 30
  batch_size: 8
  learning_rate: 0.00001
  collate_fn: True
model:
  model_name_or_path: 'bert-base-uncased'
  reg_or_class: 'reg'
  max_length: 512
  id: 0
aes:
  prompt_id: 1
  friendly_score: True
callbacks:
  patience: 2
  patience_min_delta: 0
path:
  traindata_file_name: "/content/drive/MyDrive/GoogleColab/1.AES/ASAP/data/fold_0/train.tsv"
  valdata_file_name: "/content/drive/MyDrive/GoogleColab/1.AES/ASAP/data/fold_0/dev.tsv"
  checkpoint_path: /content/drive/MyDrive/GoogleColab/1.AES/ASAP/GithubTestAES/reg/pt${aes.prompt_id}/fold_${training.fold}
  save_filename: id${model.id}