eval:
  fold: 0
  batch_size: 8
  collate_fn: True
model:
  inftype: None
  model_name_or_path: 'microsoft/deberta-v3-base'
  reg_or_class: 'mix'
  max_length: 512
  num_labels: None
  id: 0
  original_loss_weight: 50
aes:
  prompt_id: 1
  friendly_score: True
ue:
  num_dropout: 5
  ensemble_model_paths: 
    - /content/drive/MyDrive/GoogleColab/1.AES/ASAP/Mix-torchlightning/prompt${aes.prompt_id}/fold_${eval.fold}/id0_org_loss
    - /content/drive/MyDrive/GoogleColab/1.AES/ASAP/Mix-torchlightning/prompt${aes.prompt_id}/fold_${eval.fold}/id1_org_loss
    - /content/drive/MyDrive/GoogleColab/1.AES/ASAP/Mix-torchlightning/prompt${aes.prompt_id}/fold_${eval.fold}/id2_org_loss
    - /content/drive/MyDrive/GoogleColab/1.AES/ASAP/Mix-torchlightning/prompt${aes.prompt_id}/fold_${eval.fold}/id3_org_loss
    - /content/drive/MyDrive/GoogleColab/1.AES/ASAP/Mix-torchlightning/prompt${aes.prompt_id}/fold_${eval.fold}/id4_org_loss
path:
  traindata_file_name: /content/drive/MyDrive/GoogleColab/1.AES/ASAP/data/fold_${eval.fold}/train.tsv
  testdata_file_name: /content/drive/MyDrive/GoogleColab/1.AES/ASAP/data/fold_${eval.fold}/test.tsv
  model_save_path: /content/drive/MyDrive/GoogleColab/1.AES/ASAP/Mix-torchlightning/prompt${aes.prompt_id}/fold_${eval.fold}/id${model.id}_deberta
  results_save_path: /content/drive/MyDrive/GoogleColab/1.AES/ASAP/Mix-torchlightning/prompt${aes.prompt_id}/fold_${eval.fold}/pred_results
  scaler_savepath: /content/drive/MyDrive/GoogleColab/1.AES/ASAP/Mix-torchlightning/prompt${aes.prompt_id}/fold_${eval.fold}/ExpectedW_modelid${model.id}