eval:
  fold: 0
  batch_size: 8
  collate_fn: True
model:
  model_name_or_path: 'bert-base-uncased'
  reg_or_class: 'reg'
  max_length: 512
  num_labels: None
  id: 0
aes:
  prompt_id: 1
  friendly_score: True
path:
  traindata_file_name: /content/drive/MyDrive/GoogleColab/1.AES/ASAP/data/fold_${eval.fold}/train.tsv
  testdata_file_name: /content/drive/MyDrive/GoogleColab/1.AES/ASAP/data/fold_${eval.fold}/test.tsv
  model_save_path: /content/drive/MyDrive/GoogleColab/1.AES/ASAP/Mix-torchlightning/prompt${aes.prompt_id}/fold_${eval.fold}/id${model.id}
  results_save_path: /content/drive/MyDrive/GoogleColab/1.AES/ASAP/Mix-torchlightning/prompt${aes.prompt_id}/fold_${eval.fold}/pred_results