wandb:
  project: AEStest_exp
  exp_num: 1
  tags: [bert]
path:
  traindata_file_name: "/content/drive/MyDrive/GoogleColab/1.AES/ASAP/data/fold_0/train.tsv"
  devdata_file_name: "/content/drive/MyDrive/GoogleColab/1.AES/ASAP/data/fold_0/dev.tsv"
  checkpoint_path: checkpoints
training:
  test_size: 0.3
  n_epochs: 30
  batch_size: 8
  learning_rate: 0.00001
  collate_fn: True
model:
  max_length: 512
aes:
  prompt_id: 1
  friendly_score: True
callbacks:
  patience: 5
  patience_min_delta: 0